export const ADD_INGRADIENT = 'ADD_INGRADIENT';
export const REMOVE_INGRADIENT = 'REMOVE_INGRADIENT';
export const SET_INGRADIENTS = 'SET_INGRADIENTS';
export const FAILED_INGRADIENTS = 'FAILED_INGRADIENTS';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';


export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAIL = 'ORDERS_FAIL';


export const ORDERS_START = 'ORDERS_START';